" let $PATH = "/usr/local/opt/pyenv/shims:".$PATH

"set lua
" set luadll=/usr/local/Cellar/lua/5.2.4_3/lib/liblua.dylib
"vundle 対応
set nocompatible
"disable undofile
set noundofile
"Please set your own Neobundle directory.
if has('vim_starting')
  set runtimepath+=~/.dotfiles/vim/vimfiles/bundle/neobundle.vim
endif
call neobundle#begin(expand('~/.dotfiles/vim/vimfiles/bundle/'))
  NeoBundleFetch 'Shougo/neobundle.vim'

  NeoBundle 'Shougo/vimproc.vim', {
        \ 'build' : {
        \     'windows' : 'tools\\update-dll-mingw',
        \     'cygwin' : 'make -f make_cygwin.mak',
        \     'mac' : 'make',
        \     'linux' : 'make',
        \     'unix' : 'gmake',
        \    },
        \ }
  NeoBundle 'https://github.com/Shougo/unite.vim.git'
  NeoBundle 'https://github.com/Shougo/neomru.vim'
  NeoBundle 'https://github.com/Shougo/vimfiler'
  NeoBundle 'https://github.com/Shougo/neosnippet'
  NeoBundle 'https://github.com/Shougo/neosnippet-snippets'
  NeoBundle 'https://github.com/Shougo/vimshell.git'
  NeoBundle 'https://github.com/tpope/vim-rails.git'
  NeoBundle 'https://github.com/Shougo/neocomplete'
  NeoBundle 'https://github.com/nathanaelkane/vim-indent-guides'
  NeoBundle 'https://github.com/thinca/vim-quickrun.git'
  NeoBundle 'https://github.com/vim-scripts/ref.vim'
  NeoBundle 'https://github.com/bling/vim-airline'
  NeoBundle 'https://github.com/itchyny/lightline.vim.git'
  NeoBundle 'https://github.com/vim-ruby/vim-ruby'
  NeoBundle 'https://github.com/scrooloose/syntastic'
  NeoBundle 'https://github.com/tomtom/tcomment_vim'
  NeoBundle 'https://github.com/kana/vim-surround'
  NeoBundle 'https://github.com/vim-scripts/grep.vim.git'
  NeoBundle 'https://github.com/vim-scripts/sudo.vim.git'
  NeoBundle 'https://github.com/LeafCage/foldCC.git'
  NeoBundle 'https://github.com/vim-scripts/ruby-matchit.git'
  NeoBundle 'https://github.com/tpope/vim-endwise'
  NeoBundle 'https://github.com/vim-scripts/yanktmp.vim.git'
  NeoBundle 'https://github.com/h1mesuke/vim-alignta.git'
  NeoBundle 'https://github.com/slim-template/vim-slim.git'
  NeoBundle 'https://github.com/tomasr/molokai.git'
  NeoBundle 'https://github.com/vim-scripts/twilight.git'
  NeoBundle 'https://github.com/chase/vim-ansible-yaml.git'
  NeoBundle 'https://github.com/tpope/vim-fugitive.git'
  NeoBundle 'https://github.com/airblade/vim-gitgutter.git'
  NeoBundle 'https://github.com/kchmck/vim-coffee-script.git'
  NeoBundle 'https://github.com/hynek/vim-python-pep8-indent'
  NeoBundle 'https://github.com/kevinw/pyflakes-vim.git'
  " DJANGO_SETTINGS_MODULE を自動設定
  NeoBundleLazy "lambdalisue/vim-django-support", {
        \ "autoload": {
        \   "filetypes": ["python", "python3", "djangohtml"]
        \ }}
  NeoBundleLazy "jmcantrell/vim-virtualenv", {
        \ "autoload": {
        \   "filetypes": ["python", "python3", "djangohtml"]
        \ }}
  NeoBundleLazy "davidhalter/jedi-vim", {
        \ "autoload": {
        \   "filetypes": ["python", "python3", "djangohtml"],
        \ },
        \ "build": {
        \   "mac": "pip install jedi",
        \   "unix": "pip install jedi",
        \ }}
call neobundle#end()
NeoBundleCheck

filetype plugin on
filetype indent on

autocmd FileType python setl autoindent
autocmd FileType python setl smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
autocmd FileType python setl expandtab tabstop=4 shiftwidth=4 softtabstop=4
autocmd FileType python setl omnifunc=jedi#completions
autocmd FileType python setlocal completeopt-=preview
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0

if !exists('g:neocomplete#force_omni_input_patterns')
  let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^.\t]\.\w*'

" Color Scheme
colorscheme molokai
syntax on

set expandtab
set shiftwidth=2
set number
set showmatch
set clipboard=unnamed,autoselect
set ts=2 sw=2 et
set backspace=start,eol,indent
let g:indent_guides_auto_colors = 0
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=235
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237

autocmd BufRead,BufNewFile  *.md,*.MD set filetype=markdown
"保存時に行末の空白を自動で削除
autocmd BufWritePre * :%s/\s\+$//e

"Syntax check
let g:syntastic_enable_signs=1
let g:syntastic_auto_loc_list=1

"for vimfiler keymap
"vimデフォルトのエクスプローラをvimfilerで置き換える
let g:vimfiler_as_default_explorer = 1
"セーフモードを無効にした状態で起動する
let g:vimfiler_safe_mode_by_default = 0
"現在開いているバッファをIDE風に開く
nnoremap <silent> <Leader>f :<C-u>VimFilerBufferDir -split -simple -winwidth=35 -no-quit<CR>

"unite prefix key.
nnoremap [unite] <Nop>
nmap <Space>f [unite]
"bookmarkだけホームディレクトリに保存
let g:unite_source_bookmark_directory = $HOME . '/.unite/bookmark'
"現在開いているファイルのディレクトリ下のファイル一覧。
"開いていない場合はカレントディレクトリ
nnoremap <silent> [unite]f :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
"バッファ一覧
nnoremap <silent> [unite]b :<C-u>Unite buffer<CR>
"レジスタ一覧
nnoremap <silent> [unite]r :<C-u>Unite -buffer-name=register register<CR>
"最近使用したファイル一覧
nnoremap <silent> [unite]h :<C-u>Unite file_mru<CR>
"ブックマーク一覧
nnoremap <silent> [unite]c :<C-u>Unite bookmark<CR>
"ブックマークに追加
nnoremap <silent> [unite]a :<C-u>UniteBookmarkAdd<CR>

" neocomplete {{{
let g:neocomplete#enable_at_startup               = 1
let g:neocomplete#auto_completion_start_length    = 3
let g:neocomplete#enable_ignore_case              = 1
let g:neocomplete#enable_smart_case               = 1
let g:neocomplete#enable_camel_case               = 1
let g:neocomplete#use_vimproc                     = 1
let g:neocomplete#sources#buffer#cache_limit_size = 1000000
let g:neocomplete#sources#tags#cache_limit_size   = 30000000
let g:neocomplete#enable_fuzzy_completion         = 1
let g:neocomplete#lock_buffer_name_pattern        = '\*ku\*'
" }}}

"neocomplete用（自動補完）
"let g:neocomplete#enable_at_startup = 1
"区切りの補完を有効化
"let g:neocomplete#enable_underbar_completion = 1
" シンタックスをキャッシュするときの最小文字長を3
"let g:neocomplete#syntax#min_syntax_length = 3
"Enable heavy omni completion. ruby用
" if !exists('g:neocomplete#omni_patterns')
"   let g:neocomplete#omni_patterns = {}
" endif
" let g:neocomplete#omni_patterns.ruby = '[^. *¥t]¥.¥w*¥|¥h¥w*::'
" autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
"neocomplete用（自動補完）
let g:neocomplete#enable_at_startup = 1
"区切りの補完を有効化
let g:neocomplete#enable_underbar_completion = 1
" シンタックスをキャッシュするときの最小文字長を3
let g:neocomplete#source#syntax#min_syntax_length = 3
"Enable heavy omni completion. ruby用
 if !exists('g:neocomplete#omni_patterns')
   let g:neocomplete#omni_patterns = {}
 endif
let g:neocomplete#omni_patterns.ruby = '[^. *¥t]¥.¥w*¥|¥h¥w*::'
autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
let g:neocomplete#enable_auto_select = 1
" 補完候補が表示されている場合は確定。そうでない場合は改行
inoremap pumvisible() ? neocomplete#close_popup() : "¥"
let g:neocomplete#snippets_dir = '~/.vim/snippets'
" 補完をキャンセル
inoremap <expr><C-e>  neocomplete#cancel_popup()
inoremap <expr><Right> pumvisible() ? neocomplete#cancel_popup() : "\<Right>"
let g:quickrun_config = {}
let g:quickrun_config.markdown = {
    \ 'outputter':'null',
    \ 'command':'open',
    \ 'cmdopt':'-a',
    \ 'args':'Marked\ 2',
    \ 'exec':'%c %o %a %s',
    \ }
let g:quickrun_config._ = {'runner' : 'vimproc', "outputter/buffer/into" : 1}
let g:quickrun_config['ruby.rspec'] = { 'command': 'rspec', 'cmdopt': 'bundle exec foreman run --root=../..', 'exec': '%o %c %s'}
augroup RSpec
  autocmd!
  autocmd BufWinEnter,BufNewFile *_spec.rb set filetype=ruby.rspec
augroup END

" qfixsetting
set runtimepath+=~/.dotfiles/vim/qfixapp
" QuickFixウィンドウでもプレビューや絞り込みを有効化
let QFixWin_EnableMode = 1
" QFixHowm/QFixGrepの結果表示にロケーションリストを使用する/しない
let QFix_UseLocationList = 1
"Grepコマンドのキーマップ
let MyGrep_Key  = 'g'
"Grepコマンドの2ストローク目キーマップ
let MyGrep_KeyB = ''

" airline settings
" Powerlineの設定
set laststatus=2
" let g:Powerline_symbols = 'fancy'
set t_Co=256
let g:airline_powerline_fonts = 1
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'MyFugitive',
      \   'readonly': 'MyReadonly',
      \   'modified': 'MyModified',
      \   'filename': 'MyFilename',
      \   'gitgutter': 'MyGitGutter'
      \ }
      \ }

function! MyModified()
  if &filetype == "help"
    return ""
  elseif &modified
    return "+"
  elseif &modifiable
    return ""
  else
    return ""
  endif
endfunction

function! MyReadonly()
  if &filetype == "help"
    return ""
  elseif &readonly
    return "⭤"
  else
    return ""
  endif
endfunction

function! MyFugitive()
  return exists('*fugitive#head') ? fugitive#head() : ''
endfunction

function! MyFilename()
  return ('' != MyReadonly() ? MyReadonly() . ' ' : '') .
        \ ('' != expand('%:t') ? expand('%:t') : '[No Name]') .
        \ ('' != MyModified() ? ' ' . MyModified() : '')
endfunction

function! MyGitGutter()
  if ! exists('*GitGutterGetHunkSummary')
        \ || ! get(g:, 'gitgutter_enabled', 0)
        \ || winwidth('.') <= 90
    return ''
  endif
  let symbols = [
        \ g:gitgutter_sign_added . ' ',
        \ g:gitgutter_sign_modified . ' ',
        \ g:gitgutter_sign_removed . ' '
        \ ]
  let hunks = GitGutterGetHunkSummary()
  let ret = []
  for i in [0, 1, 2]
    if hunks[i] > 0
      call add(ret, symbols[i] . hunks[i])
    endif
  endfor
  return join(ret, ' ')
endfunction

set backspace=indent,eol,start
set backspace=2
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
