"vundle 対応
set nocompatible
filetype off
"Please set your own vundle directory.
set rtp+=~/dotfiles/vim/vimfiles/vundle/ 
call vundle#rc()

" vim-scripts リポジトリ
Bundle 'git://github.com/tpope/vim-rails.git'
Bundle 'Shougo/unite.vim'
Bundle 'https://github.com/Shougo/neosnippet'
Bundle 'neocomplcache'
Bundle 'nathanaelkane/vim-indent-guides'
Bundle 'http://github.com/Shougo/vimshell.git'
Bundle 'http://github.com/thinca/vim-quickrun.git'
Bundle 'https://github.com/Lokaltog/vim-powerline'
Bundle 'ref.vim'
Bundle 'git://github.com/Shougo/vimproc'

" Color Scheme
"colorscheme molokai
syntax on
colorscheme railscasts

set expandtab
set shiftwidth=2
set nocompatible
set number
set showmatch
set clipboard=unnamed,autoselect
"set ts=4 sw=4 et
let g:indent_guides_auto_colors = 0
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=7
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=3
autocmd BufRead,BufNewFile  *.md,*.MD set filetype=markdown
"保存時に行末の空白を自動で削除
autocmd BufWritePre * :%s/\s\+$//e

"neocomplcache用（自動補完）
let g:neocomplcache_enable_at_startup = 1
"区切りの補完を有効化
let g:neocomplcache_enable_underbar_completion = 1
" シンタックスをキャッシュするときの最小文字長を3
let g:neocomplcache_min_syntax_length = 3
"Enable heavy omni completion. ruby用
if !exists('g:neocomplcache_omni_patterns')
  let g:neocomplcache_omni_patterns = {}
endif
let g:neocomplcache_omni_patterns.ruby = '[^. *¥t]¥.¥w*¥|¥h¥w*::'
autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
" 閉じ括弧を自動補完
inoremap ( ()<Left>
inoremap { {}<Left>
inoremap [ []<left>

" snippetを<Tab> にマッピング
imap <expr><Tab> neocomplcache#sources#snippets_complete#expandable() ? "\<Plug>(neocomplcache_snippets_expand)" : pumvisible() ? "\<C-n>" : "\<Tab>"
" 1番目の候補を自動選択
let g:neocomplcache_enable_auto_select = 1
" 補完候補が表示されている場合は確定。そうでない場合は改行
inoremap pumvisible() ? neocomplcache#close_popup() : "¥"
" エディットのエイリアス
noremap snip :<C-u>NeoComplCacheEditSnippets<CR>
" スニペット保管場所
let g:neocomplcache_snippets_dir = '~/.vim/snippets'
" 補完をキャンセル
inoremap <expr><C-e>  neocomplcache#cancel_popup()
inoremap <expr><Right> pumvisible() ? neocomplcache#cancel_popup() : "\<Right>"
" set quickrun command
let g:quickrun_config = {}
let g:quickrun_config.markdown = {
    \ 'outputter':'null',
    \ 'command':'open',
    \ 'cmdopt':'-a',
    \ 'args':'Marked',
    \ 'exec':'%c %o %a %s',
    \ }
let g:quickrun_config._ = {'runner' : 'vimproc', "outputter/buffer/into" : 1} 
let g:quickrun_config['ruby.rspec'] = { 'command': 'rspec', 'cmdopt': 'bundle exec', 'exec': '%o %c %s'}
augroup RSpec
  autocmd!
  autocmd BufWinEnter,BufNewFile *_spec.rb set filetype=ruby.rspec
augroup END 
